version: '2'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
  agent:
    build: .
    image: cta-oss/cta-app-agent:compose
    ports:
      - "3001:3001"
    depends_on: 
      - rabbitmq

